### ISSUE TITLE
Missing Streamlit package in requirements.txt

### ISSUE THREAD

**Issue by SSAdvisor** [hassancs91/ChatGPT-MAX-3.0#2]
The Streamlit package is missing in requirements.txt.

**Comment by SSAdvisor** [comment]
Here is a diff of the requirements.txt I'm using on Linux.

[ChatGPT-MAX-3.0-requirements.diff.txt](https://github.com/hassancs91/ChatGPT-MAX-3.0/files/12677049/ChatGPT-MAX-3.0-requirements.diff.txt)

**Comment by Umark3434** [comment]
@SSAdvisor can you tell about MAC?

**Comment by hassancs91** [comment]
updated

**Comment by SSAdvisor** [comment]
@Umark3434 what do you mean?

**Comment by SSAdvisor** [comment]
> updated

Thanks for the minimal requirements.txt file. Much appreciated.
